import { randomUUID } from 'node:crypto';

/** Keys generated by the server. User filenames never become part of a key. */
export const blobKeys = {
  /** Where every artifact version's blob is, for listing them. */
  artifactsPrefix: 'artifacts',
  artifactVersion: (artifactId: string, versionNo: number) =>
    `${blobKeys.artifactsPrefix}/${artifactId}/${versionNo}-${randomUUID()}`,
  healthProbe: () => `health/${randomUUID()}`,
};
