import { randomUUID } from 'node:crypto';

/** Keys generated by the server. User filenames never become part of a key. */
export const blobKeys = {
  artifactVersion: (artifactId: string, versionNo: number) =>
    `artifacts/${artifactId}/${versionNo}-${randomUUID()}`,
  healthProbe: () => `health/${randomUUID()}`,
};
