import type { Readable } from 'node:stream';

export interface PutOptions {
  contentType: string;
  /** Expected size in bytes. When given, a body of any other length is rejected. */
  size?: number;
}

export interface PutResult {
  size: number;
  /** Lowercase hex SHA-256 of the stored bytes, computed while streaming. */
  sha256: string;
}

/** Inclusive byte range, like an HTTP `Range: bytes=start-end` header. */
export interface ByteRange {
  start: number;
  end: number;
}

export interface BlobStat {
  size: number;
}

/** A stored blob, as `StorageDriver.list` finds it. */
export interface BlobListing {
  key: string;
  /** When it was written. */
  modifiedAt: Date;
}

/**
 * Where artifact content lives. Keys are generated by the server only (`blobKeys`), never
 * derived from user input. Blobs are immutable: `put` refuses to overwrite an existing key.
 */
export interface StorageDriver {
  put(key: string, body: Readable, opts: PutOptions): Promise<PutResult>;
  /** Rejects with `BlobNotFoundError` when the key does not exist. */
  getStream(key: string, range?: ByteRange): Promise<Readable>;
  stat(key: string): Promise<BlobStat | null>;
  /** Idempotent: deleting a missing key succeeds. */
  delete(key: string): Promise<void>;
  /** Blobs whose key starts with `prefix/`, written before `olderThan`. For the sweeper. */
  list(prefix: string, olderThan: Date): AsyncIterable<BlobListing>;
  /**
   * Deletes what writes cut short by a crash left behind before `olderThan` (the local driver's
   * temporary files), and returns how many. For the sweeper.
   */
  deleteIncompleteWrites(olderThan: Date): Promise<number>;
}
