import {
  ARTIFACT_STATUSES,
  ARTIFACT_VISIBILITIES,
  type Artifact as ArtifactDto,
  type ArtifactStatus,
  type ArtifactVisibility,
  METADATA_SOURCES,
  type MetadataSource,
} from '@artifact-hub/shared';
import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
  UpdateDateColumn,
} from 'typeorm';
import { User } from '../users/user.entity.js';
import { ArtifactVersion, toArtifactVersionDto } from './artifact-version.entity.js';
import type { ArtifactView } from './artifacts.types.js';

@Entity('artifacts')
export class Artifact {
  /** Generated by the server before the insert, because the blob key contains it. */
  @PrimaryColumn('uuid')
  id: string;

  @Column('uuid')
  ownerId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn()
  owner: User;

  @Column('text')
  title: string;

  @Column('text')
  description: string;

  @Column('text', { array: true })
  tags: string[];

  /** `public` = everyone at the company can view and comment. */
  @Column({ type: 'enum', enum: ARTIFACT_VISIBILITIES, enumName: 'artifact_visibility' })
  visibility: ArtifactVisibility;

  /** The version everyone at the company sees when public; null = always the latest. */
  @Column({ type: 'uuid', nullable: true })
  publicPinnedVersionId: string | null;

  @Column({ type: 'uuid', nullable: true })
  currentVersionId: string | null;

  @ManyToOne(() => ArtifactVersion, { nullable: true })
  @JoinColumn()
  currentVersion: ArtifactVersion | null;

  @Column('int')
  latestVersionNo: number;

  @Column({ type: 'enum', enum: ARTIFACT_STATUSES, enumName: 'artifact_status' })
  status: ArtifactStatus;

  @Column({ type: 'enum', enum: METADATA_SOURCES, enumName: 'metadata_source' })
  metadataSource: MetadataSource;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;

  /** Full-text search vector, maintained by a database trigger; never read or written here. */
  @Column({ type: 'tsvector', select: false, insert: false, update: false })
  searchVector: string;

  /** Soft delete: the artifact is gone for everyone, its rows and blobs are kept. */
  @Column({ type: 'timestamptz', nullable: true })
  deletedAt: Date | null;
}

/** Requires `owner` to be loaded. */
export function toArtifactDto({
  artifact,
  currentVersion,
  latestVersionNo,
  permissions,
}: ArtifactView): ArtifactDto {
  return {
    id: artifact.id,
    title: artifact.title,
    description: artifact.description,
    tags: artifact.tags,
    visibility: artifact.visibility,
    status: artifact.status,
    metadataSource: artifact.metadataSource,
    owner: { id: artifact.owner.id, displayName: artifact.owner.displayName },
    currentVersion: currentVersion ? toArtifactVersionDto(currentVersion) : null,
    latestVersionNo,
    permissions,
    createdAt: artifact.createdAt.toISOString(),
    updatedAt: artifact.updatedAt.toISOString(),
  };
}
